[versions]
android-billingclient = "6.0.1"
android-gradke-plugin = "8.0.2"
androidx-activity = "1.7.2"
androidx-fragment = "1.6.1"
# BOM to library version mapping
# https://developer.android.com/jetpack/compose/bom/bom-mapping?hl=ja
androidx-compose-bom = "2022.10.00"
androidx-compose-material3 = "1.0.0"
androidx-compose-ui = "1.3.0"
androidx-core = "1.10.1"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.7.4"
androidx-test-espresso = "3.5.1"
androidx-test-ext = "1.1.5"
dagger-hilt = "2.45"
dagger-hilt-compiler = "2.45"
dagger-hilt-plugin = "2.45"
gson = "2.10.1"
junit = "4.13.2"
kotlin-lang = "1.8.20"
kotlinx-coroutines = "1.7.2"
json = "20230618"
robolectric = "4.9"

[libraries]
android-billingclient-billing = { module = "com.android.billingclient:billing", version.ref = "android-billingclient" }
android-billingclient-billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "android-billingclient" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3"}
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui"}
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-compose-ui"}
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-ui"}
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose-ui"}
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui"}
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui"}
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt-compiler" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json = { module = "org.json:json", version.ref = "json" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradke-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradke-plugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-lang" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt-plugin" }